// Base stats for all unit types
module.exports = {
    knight: {
        attack: 70,
        defence: 60,
        has_shield: true,
        shield_bonus: 20,
        special_abilities: [],
        speed: 2,
        initial_morale: 90,
        is_commander: false,
        is_ranged: false,
        accuracy: 0,
        is_melee_capable: true,
        range: 1,
        max_health: 100,
        cost: 100
    },
    archer: {
        attack: 45,
        defence: 20,
        has_shield: false,
        shield_bonus: 0,
        special_abilities: [],
        speed: 2,
        initial_morale: 60,
        is_commander: false,
        is_ranged: true,
        accuracy: 80,
        is_melee_capable: false,
        range: 3,
        max_health: 50,
        cost: 80
    },
    wizard: {
        attack: 85,
        defence: 10,
        has_shield: false,
        shield_bonus: 0,
        special_abilities: [],
        speed: 1,
        initial_morale: 40,
        is_commander: false,
        is_ranged: true,
        accuracy: 100,
        is_melee_capable: false,
        range: 2,
        max_health: 40,
        cost: 120
    },
    scout: {
        attack: 30,
        defence: 30,
        has_shield: false,
        shield_bonus: 0,
        special_abilities: [],
        speed: 3,
        initial_morale: 50,
        is_commander: false,
        is_ranged: false,
        accuracy: 0,
        is_melee_capable: true,
        range: 1,
        max_health: 60,
        cost: 60
    }
};